[2023-01-06 15:14:15,192] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: EL.Get_data manual__2023-01-06T15:14:13.597362+00:00 [queued]>
[2023-01-06 15:14:15,203] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: EL.Get_data manual__2023-01-06T15:14:13.597362+00:00 [queued]>
[2023-01-06 15:14:15,203] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 15:14:15,204] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-06 15:14:15,205] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 15:14:15,230] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): Get_data> on 2023-01-06 15:14:13.597362+00:00
[2023-01-06 15:14:15,238] {standard_task_runner.py:52} INFO - Started process 410 to run task
[2023-01-06 15:14:15,242] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'EL', 'Get_data', 'manual__2023-01-06T15:14:13.597362+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpyogx7pn6', '--error-file', '/tmp/tmp6gv7xqom']
[2023-01-06 15:14:15,242] {standard_task_runner.py:80} INFO - Job 8: Subtask Get_data
[2023-01-06 15:14:15,297] {task_command.py:369} INFO - Running <TaskInstance: EL.Get_data manual__2023-01-06T15:14:13.597362+00:00 [running]> on host dcfdc2efb79e
[2023-01-06 15:14:15,373] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL
AIRFLOW_CTX_TASK_ID=Get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T15:14:13.597362+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-06T15:14:13.597362+00:00
[2023-01-06 15:14:15,374] {logging_mixin.py:115} INFO - 2023-01-06
[2023-01-06 15:14:15,803] {logging_mixin.py:115} INFO - 2023-01-05
[2023-01-06 15:14:16,118] {logging_mixin.py:115} INFO - 2023-01-04
[2023-01-06 15:14:16,332] {logging_mixin.py:115} INFO - 2023-01-03
[2023-01-06 15:14:16,550] {logging_mixin.py:115} INFO - 2023-01-02
[2023-01-06 15:14:17,059] {logging_mixin.py:115} INFO - 2023-01-01
[2023-01-06 15:14:17,590] {logging_mixin.py:115} INFO - 2022-12-31
[2023-01-06 15:14:17,854] {logging_mixin.py:115} INFO - 2022-12-30
[2023-01-06 15:14:18,367] {logging_mixin.py:115} INFO - {'date': '2023-01-06T11:24:48+00:00', 'date_claimed': '2023-01-06T12:52:01+00:00', 'gare': 'Lille Europe', 'item_cat': 'Bagagerie: sacs, valises, cartables', 'item': 'Valise, sac sur roulettes', 'found/not_found': 'Objet trouv√©'}
[2023-01-06 15:14:18,368] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 21, in extractData
    year, month, day = date.split('-')
AttributeError: 'dict' object has no attribute 'split'
[2023-01-06 15:14:18,380] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=EL, task_id=Get_data, execution_date=20230106T151413, start_date=20230106T151415, end_date=20230106T151418
[2023-01-06 15:14:18,397] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task Get_data ('dict' object has no attribute 'split'; 410)
[2023-01-06 15:14:18,425] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-06 15:14:18,463] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
